name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn
    - run: yarn build 
    - name: Delete existing release and tag
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          try {
            const release = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "latest"
            })
            res = await github.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id
            })
            console.log("Deleted release latest " + " (" + release.data.id + ")")
            res = await github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/latest'
            })
            console.log("Deleted tag latest")
          } catch (error) {}
    - name: Push Build to Releases
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "dist/*"
        prerelease: true
        tag: "latest"
        token: ${{ secrets.GITHUB_TOKEN }}
